"""Strict planner-hint context injection.

This module is deliberately small. It does not compute tactics, threat,
targeting, deck summaries, relic summaries, or fallback plans. The only things
allowed into the strategy_context block are:

- short/long memory facts generated by this process;
- a validated planner-hint payload rendered in v2 field names.

Current combat facts and legal actions are rendered by state_renderer.py.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


_ALLOWED_HINT_KEYS = {
    "battle_objective",
    "enemy_focus",
    "deck_usage",
    "risk_tradeoff",
    "resource_timing",
    "potion_stance",
    "kill_order",
    "danger_notes",
}
_LEGACY_HINT_KEYS = {
    "combat_plan",
    "encounter_guide",
    "defense_policy",
    "resource_policy",
    "potion_policy",
}


def _as_dict(value: Any) -> dict[str, Any]:
    return dict(value) if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    return list(value) if isinstance(value, list) else []


def _pick(source: dict[str, Any], *keys: str, default: Any = None) -> Any:
    for key in keys:
        if key in source and source[key] is not None:
            return source[key]
    return default


def _id(value: Any) -> str:
    if isinstance(value, dict):
        return str(_pick(value, "id", "card_id", "relic_id", "monster_id", "entity_id", default="")).upper()
    return str(value or "").upper()


def _enemies(state: dict[str, Any]) -> list[dict[str, Any]]:
    battle = _as_dict(state.get("battle"))
    return [dict(enemy) for enemy in (_as_list(state.get("enemies")) or _as_list(battle.get("enemies"))) if isinstance(enemy, dict)]


def _round_number(state: dict[str, Any]) -> str:
    battle = _as_dict(state.get("battle"))
    combat = _as_dict(state.get("combat"))
    return str(_pick(battle, "round_number_raw", "round_number", default=_pick(combat, "round_number", "turn", default="?")))


def _combat_key(state: dict[str, Any]) -> str:
    run = _as_dict(state.get("run"))
    battle = _as_dict(state.get("battle"))
    explicit = str(_pick(
        battle,
        "combat_key",
        "encounter_key",
        "combat_id",
        "encounter_id",
        "encounter",
        default=_pick(state, "combat_key", "encounter_key", "combat_id", default=""),
    )).strip()
    if explicit:
        return explicit
    act = str(_pick(run, "act", default="")).strip()
    floor = str(_pick(run, "floor_reached", "floor", default="")).strip()
    seed = str(_pick(run, "seed", "run_seed", default="")).strip()
    if seed or act not in {"", "0", "-1"} or floor not in {"", "0", "-1"}:
        return f"run={seed or '-'}|act={act or '?'}|floor={floor or '?'}"
    enemies = ",".join(_id(enemy) for enemy in _enemies(state))
    return enemies or "combat"


def _join_limited(values: list[str], *, max_items: int, fallback: str = "none") -> str:
    clean = [str(value).strip() for value in values if str(value).strip()]
    if not clean:
        return fallback
    return "; ".join(clean[-max_items:])


def _action_label(action: dict[str, Any]) -> str:
    atype = str(_pick(action, "action", "action_type", "type", default="?")).lower()
    if atype == "play_card":
        card = str(_pick(action, "card_id", default="?"))
        hand_idx = _pick(action, "card_index", "hand_index", default="?")
        target = _pick(action, "target_id", "target", default=None)
        if target not in (None, "", 0, -1, "0", "-1"):
            return f"played {card} hand[{hand_idx}] -> enemy{target}"
        return f"played {card} hand[{hand_idx}]"
    if atype == "end_turn":
        return "ended turn"
    return atype or "action"


def _memory_lines(memory: str) -> list[str]:
    clean = (memory or "").strip()
    if not clean:
        return [
            "  short_term:",
            "    recent_actions: none",
            "  long_term: none",
        ]
    if not clean.startswith("short_term:"):
        raise ValueError("strategy_context_memory_must_start_with_short_term")
    return [f"  {line}" for line in clean.splitlines()]


def _planner_hint_lines(planner_hint: str) -> list[str]:
    clean = (planner_hint or "").strip()
    if not clean:
        return []
    if clean.startswith("planner_hint:"):
        clean = "\n".join(clean.splitlines()[1:]).strip()
    lines = ["  planner_hint:"]
    for raw_line in clean.splitlines():
        text = raw_line.strip()
        if not text:
            continue
        key = text.split(":", 1)[0].strip()
        if key in _LEGACY_HINT_KEYS:
            raise ValueError(f"legacy_planner_hint_field:{key}")
        if key and key not in _ALLOWED_HINT_KEYS:
            raise ValueError(f"unknown_planner_hint_field:{key}")
        lines.append(f"    {text}")
    return lines


def build_strategy_context(
    state: dict[str, Any],
    legal_actions: list[dict[str, Any]],
    history: list[str] | None = None,
    *,
    memory: str = "",
    planner_hint: str = "",
) -> str:
    _ = state, legal_actions
    actions = _join_limited(history or [], max_items=4, fallback="none")
    memory_text = memory.strip() or "\n".join([
        "short_term:",
        f"  recent_actions: {actions}",
        "long_term: none",
    ])
    return "\n".join([
        "strategy_context:",
        *_memory_lines(memory_text),
        *_planner_hint_lines(planner_hint),
    ])


def inject_strategy_context(user_message: str, strategy_context: str) -> str:
    context = (strategy_context or "").strip()
    if not context:
        return user_message
    lines = user_message.splitlines()
    if not lines:
        return context
    return "\n".join([lines[0], context, *lines[1:]])


@dataclass
class StrategyMemory:
    combat_key: str = ""
    turn_key: str = ""
    turn_actions: list[str] = field(default_factory=list)
    combat_actions: list[str] = field(default_factory=list)

    def reset(self) -> None:
        self.combat_key = ""
        self.turn_key = ""
        self.turn_actions.clear()
        self.combat_actions.clear()

    def reset_combat(self) -> None:
        self.reset()

    def _memory_text(self) -> str:
        return "\n".join([
            "short_term:",
            f"  recent_actions: {_join_limited(self.turn_actions, max_items=4, fallback='none')}",
            "long_term: none",
        ])

    def planner_memory_text(self, state: dict[str, Any]) -> str:
        _ = state
        return "\n".join([
            "short_term:",
            f"  recent_actions: {_join_limited(self.combat_actions, max_items=4, fallback='none')}",
            "long_term: none",
        ])

    def context_text(
        self,
        state: dict[str, Any],
        legal_actions: list[dict[str, Any]],
        *,
        planner_hint: str = "",
    ) -> str:
        combat = _combat_key(state)
        turn = f"{combat}::round={_round_number(state)}"
        if combat != self.combat_key:
            self.combat_key = combat
            self.turn_key = turn
            self.turn_actions.clear()
            self.combat_actions.clear()
        elif turn != self.turn_key:
            self.turn_key = turn
            self.turn_actions.clear()
        return build_strategy_context(
            state,
            legal_actions,
            self.turn_actions,
            memory=self._memory_text(),
            planner_hint=planner_hint,
        )

    def record_action(self, action: dict[str, Any] | None) -> None:
        if not isinstance(action, dict):
            return
        label = _action_label(action)
        self.turn_actions.append(label)
        self.combat_actions.append(label)
        del self.turn_actions[:-6]
        del self.combat_actions[:-8]


__all__ = [
    "StrategyMemory",
    "build_strategy_context",
    "inject_strategy_context",
]
