<Project>
  <ItemGroup>
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\BowlbugSilk.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\BygoneEffigy.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\DecimillipedeSegment.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\Flyconid.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\FuzzyWurmCrawler.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\Guardbot.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\KinFollower.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\LeafSlimeM.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\MagiKnight.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\Myte.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\Noisebot.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\PhrogParasite.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\Queen.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\SnappingJaxfruit.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\SoulNexus.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\Stabbot.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\TestSubject.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\ThievingHopper.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\TorchHeadAmalgam.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\ToughEgg.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\Tunneler.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\TwigSlimeM.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\WaterfallGiant.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\Wriggler.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory)..\..\..\..\..\src\Core\Models\Monsters\Zapbot.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)**\*.cs" Link="SrcCompat\AutoGenerated\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
