#!/usr/bin/env python3
"""
auto_stub.py - Parse dotnet build errors and generate C# stub code.

Runs `dotnet build` on HeadlessSim.csproj, parses error output, and generates
stub members/classes to fix compilation errors.

Usage:
    python auto_stub.py [--dry-run] [--csproj PATH] [--input FILE]
"""

import subprocess
import re
import sys
from collections import defaultdict
from pathlib import Path
from datetime import datetime

# ── Configuration ──────────────────────────────────────────────────────────

SCRIPT_DIR = Path(__file__).resolve().parent
HEADLESS_DIR = SCRIPT_DIR.parent / "HeadlessSim"
GODOT_STUB_DIR = SCRIPT_DIR.parent / "GodotSharpStub" / "src"
DEFAULT_CSPROJ = HEADLESS_DIR / "HeadlessSim.csproj"
OUTPUT_FILE = HEADLESS_DIR / "AutoGeneratedStubs.cs"

# ── Regex helpers ──────────────────────────────────────────────────────────
# Chinese dotnet uses \u201c\u201d; English uses double quotes

_QCHARS = '\u201c\u201d"\u2018\u2019\''


def _q():
    """Regex fragment to capture a quoted value."""
    return f'[{_QCHARS}]([^{_QCHARS}]+)[{_QCHARS}]'


RE_CS1061 = re.compile(r'error CS1061: ' + _q() + r'.*?' + _q())
RE_CS0117 = re.compile(r'error CS0117: ' + _q() + r'.*?' + _q())
RE_CS0246 = re.compile(r'error CS0246: .*?' + _q())
RE_CS0103 = re.compile(r'error CS0103: .*?' + _q())
RE_CS1501 = re.compile(r'error CS1501: ' + _q() + r'.*?(\d+)')
RE_CS1729 = re.compile(r'error CS1729: ' + _q() + r'.*?(\d+)')
RE_CS1739 = re.compile(r'error CS1739: ' + _q() + r'.*?' + _q())
RE_CS1929 = re.compile(r'error CS1929: .*?' + _q() + r'.*?' + _q())

# ── Skip lists ─────────────────────────────────────────────────────────────

SKIP_TYPES = {
    "object", "string", "int", "float", "double", "bool", "byte", "char",
    "long", "short", "uint", "ulong", "ushort", "sbyte", "decimal", "void",
    "nint", "nuint", "dynamic", "var",
    "Task", "Func", "Action", "Type", "Enum",
}

CS_KEYWORDS = {
    "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
    "char", "checked", "class", "const", "continue", "decimal", "default",
    "delegate", "do", "double", "else", "enum", "event", "explicit",
    "extern", "false", "finally", "fixed", "float", "for", "foreach",
    "goto", "if", "implicit", "in", "int", "interface", "internal",
    "is", "lock", "long", "namespace", "new", "null", "object", "operator",
    "out", "override", "params", "private", "protected", "public",
    "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof",
    "stackalloc", "static", "string", "struct", "switch", "this", "throw",
    "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe",
    "ushort", "using", "virtual", "void", "volatile", "while",
}


def _is_valid_identifier(name: str) -> bool:
    if not name:
        return False
    if name in CS_KEYWORDS:
        return False
    if "<" in name or ">" in name:
        return False
    if not (name[0].isalpha() or name[0] == "_"):
        return False
    return all(c.isalnum() or c == "_" for c in name)


def _should_skip_type(type_name: str) -> bool:
    short = type_name.split(".")[-1]
    if short in SKIP_TYPES:
        return True
    if not _is_valid_identifier(short):
        return True
    return False


# ── Build & Parse ──────────────────────────────────────────────────────────

def run_build(csproj: Path) -> str:
    print(f"Running: dotnet build {csproj}")
    # Remove any previous auto-generated stubs so we see the raw errors
    if OUTPUT_FILE.exists():
        OUTPUT_FILE.unlink()
        print("  (removed previous AutoGeneratedStubs.cs)")
    # On Windows with Chinese locale, dotnet outputs in the system codepage.
    # We capture raw bytes and try multiple encodings.
    result = subprocess.run(
        ["dotnet", "build", str(csproj)],
        capture_output=True, timeout=120,
    )
    raw = result.stdout + b"\n" + result.stderr
    # Try UTF-8 first, then GBK (Chinese Windows default)
    for enc in ["utf-8", "gbk", "cp936", "latin-1"]:
        try:
            text = raw.decode(enc)
            # Verify it looks right by checking for known error code pattern
            if "error CS" in text:
                print(f"  (decoded build output as {enc})")
                return text
        except (UnicodeDecodeError, LookupError):
            continue
    # Fallback
    return raw.decode("utf-8", errors="replace")


def parse_errors(output: str) -> dict:
    errors = {
        "CS1061": [], "CS0117": [], "CS0246": [], "CS0103": [],
        "CS1501": [], "CS1729": [], "CS1739": [], "CS1929": [],
        "other": [],
    }
    for line in output.splitlines():
        if "error CS" not in line:
            continue
        stripped = line.strip()

        if "error CS1061" in line:
            m = RE_CS1061.search(line)
            if m:
                errors["CS1061"].append({"type": m.group(1), "member": m.group(2), "line": stripped})
        elif "error CS0117" in line:
            m = RE_CS0117.search(line)
            if m:
                errors["CS0117"].append({"type": m.group(1), "member": m.group(2), "line": stripped})
        elif "error CS0246" in line:
            m = RE_CS0246.search(line)
            if m:
                errors["CS0246"].append({"type": m.group(1), "line": stripped})
        elif "error CS0103" in line:
            m = RE_CS0103.search(line)
            if m:
                errors["CS0103"].append({"name": m.group(1), "line": stripped})
        elif "error CS1501" in line:
            m = RE_CS1501.search(line)
            if m:
                errors["CS1501"].append({"method": m.group(1), "arg_count": int(m.group(2)), "line": stripped})
        elif "error CS1729" in line:
            m = RE_CS1729.search(line)
            if m:
                errors["CS1729"].append({"type": m.group(1), "arg_count": int(m.group(2)), "line": stripped})
        elif "error CS1739" in line:
            m = RE_CS1739.search(line)
            if m:
                errors["CS1739"].append({"method": m.group(1), "param": m.group(2), "line": stripped})
        elif "error CS1929" in line:
            m = RE_CS1929.search(line)
            if m:
                errors["CS1929"].append({"type": m.group(1), "member": m.group(2), "line": stripped})
        else:
            code_m = re.search(r"error (CS\d+)", line)
            code = code_m.group(1) if code_m else "unknown"
            errors["other"].append({"code": code, "line": stripped})
    return errors


# ── Stub file search ───────────────────────────────────────────────────────

def find_type_in_stubs(type_name: str):
    """Search stub files for a type definition.
    Returns (file_path, namespace, is_partial, is_static, kind) or (None, None, False, False, "class").
    kind is one of: "class", "struct", "interface", "enum".
    """
    short_name = type_name.split(".")[-1]
    base_type = type_name.split(".")[0] if "." in type_name else type_name

    for search_dir in [HEADLESS_DIR, GODOT_STUB_DIR]:
        for cs_file in search_dir.glob("*.cs"):
            # Skip our own auto-generated file
            if cs_file.name == "AutoGeneratedStubs.cs":
                continue
            try:
                content = cs_file.read_text(encoding="utf-8-sig", errors="replace")
            except Exception:
                continue
            for name in {short_name, base_type}:
                if not name or not _is_valid_identifier(name):
                    continue
                pattern = rf"((?:public|internal|private)\s+(?:(?:partial|static|sealed|abstract)\s+)*)(class|struct|interface|enum)\s+{re.escape(name)}\b"
                m = re.search(pattern, content)
                if m:
                    preceding = content[:m.start()]
                    ns_match = None
                    for ns_m in re.finditer(r"namespace\s+([\w.]+)", preceding):
                        ns_match = ns_m
                    ns = ns_match.group(1) if ns_match else None
                    modifiers = m.group(1)
                    kind = m.group(2)
                    is_partial = "partial" in modifiers
                    is_static = "static" in modifiers
                    return str(cs_file), ns, is_partial, is_static, kind
    return None, None, False, False, "class"


def infer_namespace(type_name: str, source_file: str = "") -> str:
    """Infer the namespace for a missing type.
    If source_file is given, look at its using statements to guess.
    """
    if "." in type_name:
        return type_name.rsplit(".", 1)[0]
    # Try to find in excluded game source (Nodes, Audio, etc.)
    short = type_name.split(".")[-1]
    game_src = SCRIPT_DIR.parent.parent.parent / "src" / "Core"
    try:
        import subprocess
        result = subprocess.run(
            ["grep", "-r", f"class {short}\\b\\|struct {short}\\b\\|enum {short}\\b\\|interface {short}\\b",
             str(game_src), "--include=*.cs", "-l"],
            capture_output=True, text=True, timeout=5
        )
        if result.stdout.strip():
            first_file = Path(result.stdout.strip().splitlines()[0])
            content = first_file.read_text(encoding="utf-8-sig", errors="replace")
            ns_match = re.search(r'namespace\s+([\w.]+)', content)
            if ns_match:
                return ns_match.group(1)
    except Exception:
        pass
    # Fallback: look at using statements in the error source file
    if source_file:
        try:
            content = Path(source_file).read_text(encoding="utf-8-sig", errors="replace")
            for line in content.splitlines():
                if line.strip().startswith("using ") and short in line:
                    m = re.match(r'using\s+([\w.]+)', line.strip())
                    if m:
                        return m.group(1)
        except Exception:
            pass
    return "HeadlessSim.AutoStubs"


# ── Code generation ────────────────────────────────────────────────────────

def generate_stubs(errors: dict):
    stats = {
        "instance_members": 0, "static_members": 0, "types": 0,
        "constructors": 0, "manual_fix": 0, "skipped": 0,
    }
    # key = (namespace, type_short_name)
    # NOTE: is_static is never set True on the class itself. Static members go
    # into a regular partial class. This avoids CS0260/CS0708/CS0713 errors.
    type_members = defaultdict(lambda: {"members": []})

    # Track types that exist in stubs but need `partial` added
    needs_partial = {}  # file_path -> set of type names

    # Track the kind (class/struct/interface) and static-ness for each type
    type_kinds = {}   # (ns, short) -> kind
    type_static = {}  # (ns, short) -> bool

    def _resolve_type(type_name):
        """Returns (ns, short). Also records partial/kind/static info."""
        short = type_name.split(".")[-1]
        fp, ns, is_partial, is_static, kind = find_type_in_stubs(type_name)
        if ns is None:
            ns = infer_namespace(type_name)
        if fp and not is_partial:
            needs_partial.setdefault(fp, set()).add(short)
        tk = (ns, short)
        if fp:
            type_kinds[tk] = kind
            type_static[tk] = is_static
        return ns, short

    def _add_instance_member(type_name, member):
        if _should_skip_type(type_name) or not _is_valid_identifier(member):
            stats["skipped"] += 1
            return
        ns, short = _resolve_type(type_name)
        tk = (ns, short)
        type_members[tk]["members"].append(
            f"        public void {member}(object? a = null, object? b = null, object? c = null, object? d = null) {{ }}"
        )
        stats["instance_members"] += 1

    def _add_static_member(type_name, member):
        if _should_skip_type(type_name) or not _is_valid_identifier(member):
            stats["skipped"] += 1
            return
        ns, short = _resolve_type(type_name)
        tk = (ns, short)
        type_members[tk]["members"].append(
            f"        public static object? {member} {{ get; set; }}"
        )
        stats["static_members"] += 1

    # CS1061: instance member missing
    seen = set()
    for err in errors["CS1061"]:
        key = (err["type"], err["member"])
        if key in seen:
            continue
        seen.add(key)
        _add_instance_member(err["type"], err["member"])

    # CS1929: extension method form of missing instance member
    for err in errors["CS1929"]:
        key = (err["type"], err["member"])
        if key in seen:
            continue
        seen.add(key)
        _add_instance_member(err["type"], err["member"])

    # CS0117: static member missing
    seen_static = set()
    for err in errors["CS0117"]:
        key = (err["type"], err["member"])
        if key in seen_static:
            continue
        seen_static.add(key)
        _add_static_member(err["type"], err["member"])

    # CS0246: type not found — create empty stub in correct namespace
    seen_types = set()
    for err in errors["CS0246"]:
        raw = err["type"]
        name = re.sub(r"<.*>$", "", raw)
        if name in seen_types:
            continue
        seen_types.add(name)
        if _should_skip_type(name):
            continue
        fp, _, _, _, _ = find_type_in_stubs(name)
        if fp:
            continue  # already exists
        # Extract source file from error line for namespace inference
        src_file = ""
        line_match = re.match(r'([^(]+)\(', err.get("line", ""))
        if line_match:
            src_file = line_match.group(1).strip()
        ns = infer_namespace(name, src_file)
        short = name.split(".")[-1]
        if not _is_valid_identifier(short):
            continue
        tk = (ns, short)
        if tk not in type_members:
            type_members[tk]  # creates default entry
        stats["types"] += 1

    # CS0103: name not found — same treatment
    seen_names = set()
    for err in errors["CS0103"]:
        name = err["name"]
        if name in seen_names:
            continue
        seen_names.add(name)
        if not _is_valid_identifier(name):
            continue
        if name[0].isupper():
            src_file = ""
            line_match = re.match(r'([^(]+)\(', err.get("line", ""))
            if line_match:
                src_file = line_match.group(1).strip()
            ns = infer_namespace(name, src_file)
            short = name
            if not _is_valid_identifier(short):
                continue
            tk = (ns, short)
            if tk not in type_members:
                type_members[tk]
            stats["types"] += 1

    # CS1729: missing constructor
    seen_ctor = set()
    for err in errors["CS1729"]:
        key = (err["type"], err["arg_count"])
        if key in seen_ctor:
            continue
        seen_ctor.add(key)
        type_name = err["type"]
        if _should_skip_type(type_name):
            continue
        ns, short = _resolve_type(type_name)
        if not _is_valid_identifier(short):
            continue
        tk = (ns, short)
        n = err["arg_count"]
        params = ", ".join([f"object? p{i} = null" for i in range(n)])
        type_members[tk]["members"].append(
            f"        public {short}({params}) {{ }}"
        )
        stats["constructors"] += 1

    # CS1501 & CS1739: manual fix notes
    manual_fixes = []
    seen_manual = set()
    for err in errors["CS1501"]:
        key = (err["method"], err["arg_count"])
        if key not in seen_manual:
            seen_manual.add(key)
            manual_fixes.append(f"// CS1501: {err['method']} needs {err['arg_count']}-arg overload")
            stats["manual_fix"] += 1
    for err in errors["CS1739"]:
        key = (err["method"], err["param"])
        if key not in seen_manual:
            seen_manual.add(key)
            manual_fixes.append(f"// CS1739: {err['method']} missing named param '{err['param']}'")
            stats["manual_fix"] += 1

    # ── Build C# output ──
    lines = [
        "// AUTO-GENERATED STUBS - Generated by auto_stub.py",
        "// Do not edit manually; re-run the script to regenerate.",
        f"// Generated: {datetime.now().isoformat()}",
        "",
        "#nullable enable",
        "#pragma warning disable CS0414, CS0649, CS0108",
        "",
    ]

    ns_groups = defaultdict(list)
    for (ns, short_name), info in sorted(type_members.items()):
        ns_groups[ns].append((short_name, info))

    # Patch existing stub files to add `partial` keyword where needed
    for file_path_str, type_names in needs_partial.items():
        fp = Path(file_path_str)
        try:
            content = fp.read_text(encoding="utf-8-sig", errors="replace")
        except Exception:
            continue
        changed = False
        for tname in type_names:
            # Find non-partial class/struct/interface declarations and add `partial`.
            # We need to insert `partial` right before class/struct/interface keyword.
            # E.g. "public static class X" -> "public static partial class X"
            # E.g. "public class X" -> "public partial class X"
            # Only match if `partial` is NOT already present.
            pattern = rf'((?:public|internal|private)\s+(?:(?:static|sealed|abstract)\s+)*)((?:class|struct|interface)\s+{re.escape(tname)}\b)'
            def _add_partial(m):
                prefix = m.group(1)
                rest = m.group(2)
                if 'partial' in prefix:
                    return m.group(0)  # already partial
                return prefix + 'partial ' + rest
            new_content = re.sub(pattern, _add_partial, content)
            if new_content != content:
                content = new_content
                changed = True
                print(f"  Patched {fp.name}: added 'partial' to {tname}")
        if changed:
            fp.write_text(content, encoding="utf-8")

    def _inject_members_into_file(file_path, type_name, members):
        """Inject missing members directly into a source file's class body.
        Only adds members whose name doesn't already exist in the class body.
        """
        try:
            content = file_path.read_text(encoding="utf-8-sig", errors="replace")
        except Exception:
            return
        # Find the class/struct definition
        pattern = rf'((?:public|internal)\s+(?:(?:partial|static|sealed|abstract)\s+)*(?:class|struct)\s+{re.escape(type_name)}\b[^{{]*\{{)'
        m = re.search(pattern, content)
        if not m:
            return
        # Find the matching closing brace
        brace_start = m.end() - 1
        depth = 0
        close_pos = -1
        for i in range(brace_start, len(content)):
            if content[i] == '{': depth += 1
            elif content[i] == '}':
                depth -= 1
                if depth == 0:
                    close_pos = i
                    break
        if close_pos == -1:
            return
        # Get existing class body to check for duplicates
        class_body = content[m.end():close_pos]
        # Filter: only add members whose identifier doesn't already appear in class body
        new_members = []
        for member_line in members:
            # Extract the key identifier (method/property name)
            # Patterns: "public void Foo(" or "public static object? Bar { get;"
            name_match = re.search(r'(?:void|object\?|bool|int|string|float)\s+(\w+)\s*[({]', member_line)
            if not name_match:
                name_match = re.search(r'public\s+(?:static\s+)?(?:\S+\s+)?(\w+)\s*[({]', member_line)
            if name_match:
                name = name_match.group(1)
                if name == type_name:
                    # Constructor — check if same arg count exists
                    continue  # skip constructors for safety
                if re.search(rf'\b{re.escape(name)}\b', class_body):
                    continue  # already exists
            new_members.append(member_line)
        if not new_members:
            return
        injection = "\n" + "\n".join(new_members) + "\n    "
        new_content = content[:close_pos] + injection + content[close_pos:]
        file_path.write_text(new_content, encoding="utf-8")

    # Split types: GodotSharpStub types get patched in-place, HeadlessSim types go to AutoGeneratedStubs
    filtered_ns_groups = defaultdict(list)
    godot_stub_dir_str = str(GODOT_STUB_DIR.resolve())
    for (ns, short_name), info in sorted(type_members.items()):
        existing_file, existing_ns, _, _, existing_kind = find_type_in_stubs(short_name)
        if existing_file and existing_ns == ns:
            if not info["members"]:
                stats["skipped"] += 1
                continue
            # Check if this type lives in GodotSharpStub (different assembly)
            if Path(existing_file).resolve().is_relative_to(GODOT_STUB_DIR.resolve()):
                # Type lives in GodotSharpStub — inject members into that file directly
                _inject_members_into_file(Path(existing_file), short_name, info["members"])
                print(f"  Injected into GodotSharpStub: {short_name} ({len(info['members'])} members)")
            else:
                # HeadlessSim assembly — safe to use partial class in AutoGeneratedStubs
                filtered_ns_groups[ns].append((short_name, info))
        else:
            filtered_ns_groups[ns].append((short_name, info))

    for ns in sorted(filtered_ns_groups.keys()):
        lines.append(f"namespace {ns}")
        lines.append("{")
        for short_name, info in sorted(filtered_ns_groups[ns], key=lambda x: x[0]):
            tk = (ns, short_name)
            kind = type_kinds.get(tk, "class")
            is_static = type_static.get(tk, False)
            # Interfaces can't have method implementations
            if kind == "interface":
                if info["members"]:
                    manual_fixes.append(f"// SKIP: {ns}.{short_name} is an interface, can't add partial members")
                    stats["manual_fix"] += 1
                continue
            # Enums can't be extended
            if kind == "enum":
                continue
            # For static classes, filter out instance members
            members = info["members"]
            if is_static:
                filtered_members = [m for m in members if "static" in m]
                if len(filtered_members) < len(members):
                    skipped_count = len(members) - len(filtered_members)
                    manual_fixes.append(
                        f"// SKIP: {ns}.{short_name} is static, skipped {skipped_count} instance member(s)")
                    stats["manual_fix"] += 1
                members = filtered_members
            if not members and kind == "class":
                # Empty partial class with no members -- skip
                continue
            static_kw = "static " if is_static else ""
            lines.append(f"    public {static_kw}partial {kind} {short_name}")
            lines.append("    {")
            for member_line in members:
                lines.append(member_line)
            lines.append("    }")
            lines.append("")
        lines.append("}")
        lines.append("")

    if manual_fixes:
        lines.append("// ── Manual fixes needed ──")
        for note in manual_fixes:
            lines.append(note)
        lines.append("")

    return "\n".join(lines), stats


# ── Summary ────────────────────────────────────────────────────────────────

def print_summary(errors: dict, stats: dict, output_path: Path):
    total = sum(len(v) for v in errors.values())
    print("\n" + "=" * 70)
    print("AUTO-STUB SUMMARY REPORT")
    print("=" * 70)
    print(f"\nTotal build errors parsed: {total}")
    print("\nErrors by category:")
    labels = {
        "CS1061": "missing instance member",
        "CS0117": "missing static member",
        "CS0246": "type not found",
        "CS0103": "name not found",
        "CS1501": "wrong arg count (manual)",
        "CS1729": "missing constructor",
        "CS1739": "named param mismatch (manual)",
        "CS1929": "extension method missing",
        "other": "other errors",
    }
    for code in ["CS1061", "CS0117", "CS0246", "CS0103", "CS1501", "CS1729", "CS1739", "CS1929", "other"]:
        count = len(errors.get(code, []))
        if count > 0:
            print(f"  {code:8s}: {count:4d}  ({labels.get(code, '')})")

    print(f"\nStubs generated:")
    print(f"  Instance methods/props: {stats['instance_members']}")
    print(f"  Static methods/props:   {stats['static_members']}")
    print(f"  New type stubs:         {stats['types']}")
    print(f"  Constructors:           {stats['constructors']}")
    print(f"  Skipped (built-in):     {stats['skipped']}")
    print(f"  Need manual fixing:     {stats['manual_fix']}")
    print(f"\nOutput written to: {output_path}")
    print("=" * 70)


# ── Main ───────────────────────────────────────────────────────────────────

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Auto-generate C# stubs from build errors")
    parser.add_argument("--dry-run", action="store_true", help="Parse errors but don't write output")
    parser.add_argument("--csproj", type=Path, default=DEFAULT_CSPROJ, help="Path to .csproj file")
    parser.add_argument("--input", type=Path, default=None,
                        help="Read build output from file instead of running build")
    args = parser.parse_args()

    if args.input:
        print(f"Reading build output from {args.input}")
        output = args.input.read_text(encoding="utf-8", errors="replace")
    else:
        output = run_build(args.csproj)

    errors = parse_errors(output)
    total = sum(len(v) for v in errors.values())
    print(f"Parsed {total} errors from build output")

    if total == 0:
        print("No errors found - build is clean!")
        return

    code, stats = generate_stubs(errors)

    if not args.dry_run:
        OUTPUT_FILE.write_text(code, encoding="utf-8")
        print(f"Wrote stubs to {OUTPUT_FILE}")
    else:
        print("\n--- DRY RUN - Generated code: ---")
        print(code)

    print_summary(errors, stats, OUTPUT_FILE)


if __name__ == "__main__":
    main()
