#!/usr/bin/env python3
"""
Fix stubs based on build error analysis.
1. Convert methods-that-should-be-properties (CS0119 errors)
2. Add missing type stubs (CS0246/CS0103 errors)
"""
import re, os, sys
from collections import Counter, defaultdict

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(SCRIPTS_DIR, "..", "..", ".."))
STUB_DIR = os.path.join(ROOT, "tools", "headless-sim", "GodotSharpStub", "src")
AUTO_STUBS = os.path.join(ROOT, "tools", "headless-sim", "HeadlessSim", "AutoGeneratedStubs.cs")

def load_build_errors():
    path = os.path.join(SCRIPTS_DIR, "build_output.txt")
    with open(path, encoding="utf-8") as f:
        return f.readlines()

def extract_cs0119_fixes(lines):
    """Extract property names that are wrongly stubbed as methods."""
    fixes = []  # (ClassName, MemberName)
    for l in lines:
        if "error CS0119" not in l:
            continue
        # Pattern: "NCombatRoom.CombatVfxContainer(object?, ...)" is a method
        m = re.search(r'[\u201c"](\w+)\.(\w+)\(', l)
        if m:
            fixes.append((m.group(1), m.group(2)))
    return Counter(fixes)

def extract_cs0246_types(lines):
    """Extract missing type names from CS0246."""
    names = []
    for l in lines:
        if "error CS0246" not in l:
            continue
        m = re.search(r'[\u201c"](\w+)[\u201d"]', l)
        if m:
            names.append(m.group(1))
    return Counter(names)

def extract_cs0103_names(lines):
    """Extract missing names from CS0103 (used as static or direct references)."""
    names = []
    for l in lines:
        if "error CS0103" not in l:
            continue
        m = re.search(r'[\u201c"](\w+)[\u201d"]', l)
        if m:
            names.append(m.group(1))
    return Counter(names)

def fix_methods_to_properties(stub_dir):
    """In all stub .cs files, convert void Method(object? a = null, ...) to object? Property { get; set; }
    for members that appear in CS0119 errors."""
    lines = load_build_errors()
    fixes = extract_cs0119_fixes(lines)

    # Build set of member names to fix
    members_to_fix = set()
    for (cls, member), count in fixes.items():
        members_to_fix.add(member)

    print(f"Members to convert from method to property: {len(members_to_fix)}")
    for m in sorted(members_to_fix):
        print(f"  {m}")

    # Pattern: public void MemberName(object? a = null, object? b = null, object? c = null, object? d = null) { }
    method_pattern = re.compile(
        r'public\s+void\s+(\w+)\s*\(\s*object\?\s+\w+\s*=\s*null'
        r'(?:\s*,\s*object\?\s+\w+\s*=\s*null)*\s*\)\s*\{\s*\}'
    )

    total_fixes = 0
    for fname in os.listdir(stub_dir):
        if not fname.endswith('.cs'):
            continue
        fpath = os.path.join(stub_dir, fname)
        with open(fpath, encoding='utf-8') as f:
            content = f.read()

        def replacer(m):
            name = m.group(1)
            if name in members_to_fix:
                return f"public object? {name} {{ get; set; }}"
            return m.group(0)

        new_content = method_pattern.sub(replacer, content)
        if new_content != content:
            fixes_count = sum(1 for a, b in zip(content.split('\n'), new_content.split('\n')) if a != b)
            print(f"  Fixed {fixes_count} methods->properties in {fname}")
            total_fixes += fixes_count
            with open(fpath, 'w', encoding='utf-8') as f:
                f.write(new_content)

    print(f"Total method->property fixes: {total_fixes}")

def find_type_namespace(type_name):
    """Try to find the namespace for a type by searching the source."""
    src_dir = os.path.join(ROOT, "src")
    # Search for class/enum/struct/interface definition
    for dirpath, dirnames, filenames in os.walk(src_dir):
        for fname in filenames:
            if not fname.endswith('.cs') or fname.endswith('.uid'):
                continue
            fpath = os.path.join(dirpath, fname)
            try:
                with open(fpath, encoding='utf-8') as f:
                    content = f.read()
            except:
                continue
            # Check if this file defines the type
            if re.search(rf'\b(class|enum|struct|interface)\s+{re.escape(type_name)}\b', content):
                # Extract namespace
                ns_match = re.search(r'namespace\s+([\w.]+)', content)
                if ns_match:
                    return ns_match.group(1)
    return None

def main():
    print("=== Step 1: Fix methods that should be properties (CS0119) ===")
    fix_methods_to_properties(STUB_DIR)

    print("\n=== Step 2: Analyze remaining missing types ===")
    lines = load_build_errors()
    cs246 = extract_cs0246_types(lines)
    cs103 = extract_cs0103_names(lines)

    # Collect all missing type names
    all_missing = set(cs246.keys()) | set(cs103.keys())
    print(f"Total unique missing names: {len(all_missing)}")

    # Try to find their namespaces
    ns_map = {}
    for name in sorted(all_missing):
        ns = find_type_namespace(name)
        if ns:
            ns_map[name] = ns
            print(f"  Found: {name} -> {ns}")
        else:
            print(f"  NOT FOUND: {name}")

    print(f"\nFound {len(ns_map)}/{len(all_missing)} types in source")

if __name__ == "__main__":
    main()
