#!/usr/bin/env python3
"""
Generate stub declarations for all missing types found in build errors.
Reads the source to determine type kind (class/enum/struct/interface) and base class,
then generates minimal stubs.
"""
import re, os, sys
from collections import Counter, defaultdict

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(SCRIPTS_DIR, "..", "..", ".."))
SRC_DIR = os.path.join(ROOT, "src")
STUB_DIR = os.path.join(ROOT, "tools", "headless-sim", "GodotSharpStub", "src")
AUTO_STUBS = os.path.join(ROOT, "tools", "headless-sim", "HeadlessSim", "AutoGeneratedStubs.cs")

def load_build_errors():
    path = os.path.join(SCRIPTS_DIR, "build_output.txt")
    with open(path, encoding="utf-8") as f:
        return f.readlines()

def get_missing_types(lines):
    """Get all missing type/name references."""
    types = set()
    for l in lines:
        if "error CS0246" in l or "error CS0103" in l:
            m = re.search(r'[\u201c"](\w+)[\u201d"]', l)
            if m:
                types.add(m.group(1))
    return types

def find_type_info(type_name):
    """Find namespace, kind, base class, and key members for a type."""
    for dirpath, dirnames, filenames in os.walk(SRC_DIR):
        for fname in filenames:
            if not fname.endswith('.cs') or fname.endswith('.uid'):
                continue
            fpath = os.path.join(dirpath, fname)
            try:
                with open(fpath, encoding='utf-8') as f:
                    content = f.read()
            except:
                continue

            # Check if this file defines the type
            type_match = re.search(
                rf'public\s+(?:partial\s+)?(?:static\s+)?(class|enum|struct|interface)\s+{re.escape(type_name)}\b([^{{]*)',
                content
            )
            if not type_match:
                continue

            kind = type_match.group(1)
            rest = type_match.group(2).strip()

            ns_match = re.search(r'namespace\s+([\w.]+)', content)
            namespace = ns_match.group(1) if ns_match else "Unknown"

            # Check if it's static
            is_static = bool(re.search(
                rf'public\s+(?:partial\s+)?static\s+{kind}\s+{re.escape(type_name)}\b',
                content
            ))

            # Extract base class
            base_class = None
            base_match = re.match(r'\s*:\s*([\w.<>]+)', rest)
            if base_match:
                base_class = base_match.group(1)

            # For classes, find static members (Create, AssetPaths, Instance)
            static_members = []
            if kind == "class":
                if re.search(r'public\s+static\s+.*\bCreate\b', content):
                    static_members.append("Create")
                if re.search(r'public\s+static\s+.*\bAssetPaths\b', content):
                    static_members.append("AssetPaths")
                if re.search(r'public\s+static\s+.*\bInstance\b', content):
                    static_members.append("Instance")

            # For enums, extract values
            enum_values = []
            if kind == "enum":
                # Find the enum body
                enum_start = content.find(type_match.group(0))
                brace_start = content.find('{', enum_start)
                brace_end = content.find('}', brace_start)
                if brace_start > 0 and brace_end > 0:
                    body = content[brace_start+1:brace_end]
                    for line in body.split('\n'):
                        line = line.strip().rstrip(',')
                        if line and not line.startswith('//'):
                            # Could be "Name = Value" or just "Name"
                            val_match = re.match(r'(\w+)(?:\s*=\s*(.+))?', line)
                            if val_match:
                                enum_values.append(val_match.group(0))

            return {
                'name': type_name,
                'namespace': namespace,
                'kind': kind,
                'is_static': is_static,
                'base_class': base_class,
                'static_members': static_members,
                'enum_values': enum_values,
                'source_path': fpath,
            }
    return None

def check_already_stubbed(type_name, stub_dir):
    """Check if a type is already defined in stub files."""
    for fname in os.listdir(stub_dir):
        if not fname.endswith('.cs'):
            continue
        fpath = os.path.join(stub_dir, fname)
        try:
            with open(fpath, encoding='utf-8') as f:
                content = f.read()
        except:
            continue
        if re.search(rf'\b(class|enum|struct|interface)\s+{re.escape(type_name)}\b', content):
            return True
    # Also check AutoGeneratedStubs
    try:
        with open(AUTO_STUBS, encoding='utf-8') as f:
            content = f.read()
        if re.search(rf'\b(class|enum|struct|interface)\s+{re.escape(type_name)}\b', content):
            return True
    except:
        pass
    return False

def generate_stub(info):
    """Generate a stub declaration for a type."""
    name = info['name']
    kind = info['kind']

    if kind == 'enum':
        vals = info['enum_values']
        if not vals:
            vals = ['None']
        body = ', '.join(vals)
        return f"    public enum {name} {{ {body} }}"

    if kind == 'interface':
        return f"    public interface {name} {{ }}"

    if kind == 'struct':
        return f"    public struct {name} {{ }}"

    # Class
    static = "static " if info['is_static'] else ""
    base = ""
    if info['base_class']:
        bc = info['base_class']
        # Map Godot types
        if bc in ('Node', 'Node2D', 'Control', 'Resource', 'GodotObject'):
            bc = f"Godot.{bc}"
        elif bc.startswith('N') and bc[1:2].isupper():
            pass  # Keep as-is, it's a game type
        base = f" : {bc}"

    members = []
    for sm in info['static_members']:
        if sm == "Instance":
            members.append(f"        public static {name}? Instance {{ get; set; }}")
        elif sm == "Create":
            members.append(f"        public static object? Create {{ get; set; }}")
        elif sm == "AssetPaths":
            members.append(f"        public static System.Collections.Generic.IEnumerable<string> AssetPaths => System.Array.Empty<string>();")

    body = "\n".join(members)
    if body:
        body = "\n" + body + "\n    "

    return f"    public {static}partial class {name}{base} {{ {body}}}"


def main():
    print("=== Generating missing type stubs ===")
    lines = load_build_errors()
    missing = get_missing_types(lines)
    print(f"Total missing names: {len(missing)}")

    # Group by namespace
    ns_stubs = defaultdict(list)
    not_found = []
    already_stubbed = []

    for name in sorted(missing):
        if check_already_stubbed(name, STUB_DIR):
            already_stubbed.append(name)
            continue

        info = find_type_info(name)
        if info:
            stub = generate_stub(info)
            ns_stubs[info['namespace']].append(stub)
        else:
            not_found.append(name)

    print(f"Already stubbed: {len(already_stubbed)}")
    print(f"Generated stubs: {sum(len(v) for v in ns_stubs.values())}")
    print(f"Not found in source: {len(not_found)}")
    for n in not_found:
        print(f"  {n}")

    # Generate the output file
    output_lines = [
        "// AUTO-GENERATED STUBS for missing types",
        "// Generated by gen_missing_stubs.py",
        "#nullable enable",
        "#pragma warning disable CS0414, CS0649, CS0108, CS0114",
        "",
    ]

    for ns in sorted(ns_stubs.keys()):
        output_lines.append(f"namespace {ns}")
        output_lines.append("{")
        for stub in ns_stubs[ns]:
            output_lines.append(stub)
        output_lines.append("}")
        output_lines.append("")

    # Add stubs for types not found in source (Steamworks, Godot, etc.)
    # These need manual definitions
    steam_types = [n for n in not_found if n.startswith('Steam') or n.startswith('ELobby') or n.startswith('ESteam') or n.startswith('Lobby') or n == 'CGameID']
    godot_types = [n for n in not_found if n in ('Marker2D', 'InputEventPanGesture', 'CanvasGroup', 'TranslationServer')]
    migration_types = [n for n in not_found if 'Save' in n or 'History' in n or 'Serializable' in n]

    if steam_types:
        output_lines.append("namespace Steamworks")
        output_lines.append("{")
        for st in steam_types:
            if st.startswith('E'):
                output_lines.append(f"    public enum {st} {{ None }}")
            elif st.endswith('_t'):
                output_lines.append(f"    public struct {st} {{ }}")
            elif st == 'CGameID':
                output_lines.append(f"    public struct CGameID {{ public ulong m_GameID; }}")
            else:
                output_lines.append(f"    public static class {st} {{ }}")
        output_lines.append("}")
        output_lines.append("")

    if godot_types:
        output_lines.append("namespace Godot")
        output_lines.append("{")
        for gt in godot_types:
            if gt == 'Marker2D':
                output_lines.append(f"    public partial class Marker2D : Node2D {{ }}")
            elif gt == 'InputEventPanGesture':
                output_lines.append(f"    public partial class InputEventPanGesture : InputEvent {{ }}")
            elif gt == 'CanvasGroup':
                output_lines.append(f"    public partial class CanvasGroup : Node2D {{ }}")
            elif gt == 'TranslationServer':
                output_lines.append(f"    public static class TranslationServer {{ public static string Translate(string key) => key; public static void SetLocale(string locale) {{ }} public static string GetLocale() => \"en\"; }}")
        output_lines.append("}")
        output_lines.append("")

    if migration_types:
        output_lines.append("namespace MegaCrit.Sts2.Core.Saves.Migrations")
        output_lines.append("{")
        for mt in migration_types:
            output_lines.append(f"    public class {mt} {{ }}")
        output_lines.append("}")
        output_lines.append("")

    # Write output
    output_path = os.path.join(ROOT, "tools", "headless-sim", "HeadlessSim", "GeneratedMissingStubs.cs")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(output_lines))
    print(f"\nWrote stubs to: {output_path}")


if __name__ == "__main__":
    main()
