#!/usr/bin/env python3
"""根据 headless UI 风险报告批量生成 auto-generated compat 源码和 props。"""
from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_REPORT = (
    REPO_ROOT
    / "STS2AI"
    / "Artifacts"
    / "headless_ui_risk_scan"
    / "headless_ui_risk_scan_20260418_compiled_monsters.json"
)
GENERATED_ROOT = REPO_ROOT / "STS2AI" / "ENV" / "Sim" / "SrcCompat" / "AutoGenerated"
PROPS_FILE = GENERATED_ROOT / "headless_generated_compats.props"


@dataclass(frozen=True)
class Transform:
    name: str
    pattern: re.Pattern[str]
    replacement: str | None = None


TRANSFORMS: tuple[Transform, ...] = (
    Transform(
        "try_do_hit_stop",
        re.compile(r"\bNGame\.Instance(?:\?)?\.DoHitStop\("),
        "HeadlessVisualCompat.TryDoHitStop(",
    ),
    Transform(
        "try_screen_shake_trauma",
        re.compile(r"\bNGame\.Instance(?:\?)?\.ScreenShakeTrauma\("),
        "HeadlessVisualCompat.TryScreenShakeTrauma(",
    ),
    Transform(
        "try_screen_shake",
        re.compile(r"\bNGame\.Instance(?:\?)?\.ScreenShake\("),
        "HeadlessVisualCompat.TryScreenShake(",
    ),
    Transform(
        "try_screen_rumble",
        re.compile(r"\bNGame\.Instance(?:\?)?\.ScreenRumble\("),
        "HeadlessVisualCompat.TryScreenRumble(",
    ),
    Transform(
        "viewport_center_or_zero",
        re.compile(r"\bNGame\.Instance(?:\?)?\.GetViewportRect\(\)\.Size\s*/\s*2f\b"),
        "HeadlessVisualCompat.GetViewportCenterOrZero()",
    ),
    Transform(
        "try_add_combat_vfx",
        re.compile(r"\bNCombatRoom\.Instance(?:\?)?\.CombatVfxContainer(?:\?)?\.AddChildSafely\("),
        "HeadlessVisualCompat.TryAddCombatVfx(",
    ),
    Transform(
        "try_add_back_combat_vfx",
        re.compile(r"\bNCombatRoom\.Instance(?:\?)?\.BackCombatVfxContainer(?:\?)?\.AddChildSafely\("),
        "HeadlessVisualCompat.TryAddBackCombatVfx(",
    ),
    Transform(
        "try_add_global_ui",
        re.compile(r"\bNGame\.Instance(?:\?)?\.CurrentRunNode(?:\?)?\.GlobalUi(?:\?)?\.AddChildSafely\("),
        "HeadlessVisualCompat.TryAddGlobalUi(",
    ),
    Transform(
        "try_get_background_node",
        re.compile(r"\bNCombatRoom\.Instance(?:\?)?\.Background(?:\?)?\.GetNode<"),
        "HeadlessVisualCompat.TryGetBackgroundNode<",
    ),
    Transform(
        "try_get_creature_node",
        re.compile(r"\bNCombatRoom\.Instance(?:\?)?\.GetCreatureNode\("),
        "HeadlessVisualCompat.TryGetCreatureNode(",
    ),
    Transform(
        "try_set_fabricator_bot_fall_position",
        re.compile(r"\bFabricatorNormal\.SetBotFallPosition\("),
        "HeadlessVisualCompat.TrySetFabricatorBotFallPosition(",
    ),
)

SPECIAL_NODE_PATTERN = re.compile(
    r"\(?(?P<owner>HeadlessVisualCompat\.TryGetCreatureNode\(.+?\)|NCombatRoom\.Instance(?:\?)?\.GetCreatureNode\(.+?\)|\b[A-Za-z_][A-Za-z0-9_]*)\)?"
    r"(?:\?)?\.GetSpecialNode<(?P<generic>[^>]+)>\((?P<arg>.+?)\)"
)
INLINE_CREATURE_GLOBAL_POSITION_PATTERN = re.compile(
    r"HeadlessVisualCompat\.TryGetCreatureNode\((?P<arg>.+?)\)\.GlobalPosition\b"
)
ASSIGNMENT_RE = re.compile(
    r"\b(?:var|[A-Za-z_][A-Za-z0-9_<>,.?]*)\s+(?P<var>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?P<expr>.+?);"
)
NULLABLE_CREATURE_HINTS = (
    "HeadlessVisualCompat.TryGetCreatureNode(",
    "NCombatRoom.Instance?.GetCreatureNode(",
)
NULLABLE_NODE_HINTS = (
    "HeadlessVisualCompat.TryGetSpecialNode<",
    "HeadlessVisualCompat.TryGetBackgroundNode<",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--report",
        type=Path,
        default=DEFAULT_REPORT,
        help="风险报告 JSON 路径。",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=10,
        help="按风险频次选择前 N 个源文件。",
    )
    parser.add_argument(
        "--match",
        default="",
        help="只处理文件名或路径里包含该子串的条目。",
    )
    parser.add_argument(
        "--write-files",
        action="store_true",
        help="把生成结果写到 STS2AI/ENV/Sim/SrcCompat/AutoGenerated。",
    )
    return parser.parse_args()


def load_candidates(report_path: Path, *, top: int, match: str) -> list[tuple[Path, int]]:
    report = json.loads(report_path.read_text(encoding="utf-8"))
    counter: Counter[Path] = Counter()
    for finding in report["findings"]:
        if finding["mitigation"] not in {"add_overlay_compat", "add_src_compat"}:
            continue
        file_path = Path(finding["file"])
        if not str(file_path).startswith(str((REPO_ROOT / "src" / "Core" / "Models").resolve())):
            continue
        rel = file_path.resolve().relative_to(REPO_ROOT.resolve()).as_posix()
        if match and match.lower() not in rel.lower():
            continue
        counter[file_path.resolve()] += 1
    return counter.most_common(top)


def ensure_helpers_using(text: str) -> str:
    helper_using = "using MegaCrit.Sts2.Core.Helpers;\n"
    if helper_using in text:
        return text
    lines = text.splitlines(keepends=True)
    insert_at = 0
    while insert_at < len(lines) and lines[insert_at].startswith("using "):
        insert_at += 1
    lines.insert(insert_at, helper_using)
    return "".join(lines)


def rewrite_special_nodes(text: str) -> tuple[str, int]:
    count = 0

    def repl(match: re.Match[str]) -> str:
        nonlocal count
        count += 1
        return (
            f"HeadlessVisualCompat.TryGetSpecialNode<{match.group('generic')}>"
            f"({match.group('owner')}, {match.group('arg')})"
        )

    return SPECIAL_NODE_PATTERN.sub(repl, text), count


def rewrite_inline_creature_global_positions(text: str) -> tuple[str, int]:
    count = 0

    def repl(match: re.Match[str]) -> str:
        nonlocal count
        count += 1
        return (
            "HeadlessVisualCompat.GetGlobalPositionOrZero("
            f"HeadlessVisualCompat.TryGetCreatureNode({match.group('arg')}))"
        )

    return INLINE_CREATURE_GLOBAL_POSITION_PATTERN.sub(repl, text), count


def collect_nullable_vars(text: str) -> dict[str, str]:
    nullable_vars: dict[str, str] = {}
    for line in text.splitlines():
        match = ASSIGNMENT_RE.search(line)
        if match is None:
            continue
        var_name = match.group("var")
        expr = match.group("expr")
        if any(hint in expr for hint in NULLABLE_CREATURE_HINTS):
            nullable_vars[var_name] = "creature"
            continue
        if any(hint in expr for hint in NULLABLE_NODE_HINTS):
            nullable_vars[var_name] = "node"
    return nullable_vars


def rewrite_nullable_var_accesses(text: str) -> tuple[str, Counter[str]]:
    counts: Counter[str] = Counter()
    nullable_vars = collect_nullable_vars(text)
    for var_name, kind in sorted(nullable_vars.items()):
        escaped = re.escape(var_name)

        add_child_pattern = re.compile(
            rf"(?m)^(?P<indent>\s*){escaped}\.AddChildSafely\((?P<child>.+?)\);$"
        )
        text, num = add_child_pattern.subn(
            lambda match: (
                f"{match.group('indent')}HeadlessVisualCompat.TryAddChild"
                f"({var_name}, {match.group('child')});"
            ),
            text,
        )
        if num:
            counts["try_add_child"] += num

        if kind == "creature":
            body_node_pattern = re.compile(
                rf"\b{escaped}\.Visuals\.GetCurrentBody\(\)\.GetNode<(?P<generic>[^>]+)>\((?P<arg>.+?)\)"
            )
            text, num = body_node_pattern.subn(
                lambda match: (
                    f"HeadlessVisualCompat.TryGetCurrentBodyNode<{match.group('generic')}>"
                    f"({var_name}, {match.group('arg')})"
                ),
                text,
            )
            if num:
                counts["try_get_current_body_node"] += num

            text, num = re.subn(
                rf"\b{escaped}\.Visuals\.GetCurrentBody\(\)\.Scale\.X\b",
                f"HeadlessVisualCompat.GetCurrentBodyScaleXOrOne({var_name})",
                text,
            )
            if num:
                counts["current_body_scale_x_or_one"] += num

            text, num = re.subn(
                rf"\b{escaped}\.Visuals\.GetCurrentBody\(\)\.Scale\b",
                f"HeadlessVisualCompat.GetCurrentBodyScaleOrOne({var_name})",
                text,
            )
            if num:
                counts["current_body_scale_or_one"] += num

            text, num = re.subn(
                rf"\b{escaped}\.Body\.Scale\b",
                f"HeadlessVisualCompat.GetBodyScaleOrOne({var_name})",
                text,
            )
            if num:
                counts["body_scale_or_one"] += num

        position_offset_pattern = re.compile(
            rf"(?m)^(?P<indent>\s*){escaped}\.Position\s*\+=\s*(?P<expr>.+?);$"
        )
        text, num = position_offset_pattern.subn(
            lambda match: (
                f"{match.group('indent')}HeadlessVisualCompat.TryOffsetPosition"
                f"({var_name}, {match.group('expr')});"
            ),
            text,
        )
        if num:
            counts["try_offset_position"] += num

        position_set_pattern = re.compile(
            rf"(?m)^(?P<indent>\s*){escaped}\.Position\s*=\s*(?P<expr>.+?);$"
        )
        text, num = position_set_pattern.subn(
            lambda match: (
                f"{match.group('indent')}HeadlessVisualCompat.TrySetPosition"
                f"({var_name}, {match.group('expr')});"
            ),
            text,
        )
        if num:
            counts["try_set_position"] += num

        global_position_set_pattern = re.compile(
            rf"(?m)^(?P<indent>\s*){escaped}\.GlobalPosition\s*=\s*(?P<expr>.+?);$"
        )
        text, num = global_position_set_pattern.subn(
            lambda match: (
                f"{match.group('indent')}HeadlessVisualCompat.TrySetGlobalPosition"
                f"({var_name}, {match.group('expr')});"
            ),
            text,
        )
        if num:
            counts["try_set_global_position"] += num

        text, num = re.subn(
            rf"\b{escaped}\.GlobalPosition\b",
            f"HeadlessVisualCompat.GetGlobalPositionOrZero({var_name})",
            text,
        )
        if num:
            counts["global_position_or_zero"] += num

    return text, counts


def apply_transforms(text: str) -> tuple[str, Counter[str]]:
    counts: Counter[str] = Counter()
    for transform in TRANSFORMS:
        updated, num = transform.pattern.subn(transform.replacement or "", text)
        if num:
            counts[transform.name] += num
            text = updated

    text, special_count = rewrite_special_nodes(text)
    if special_count:
        counts["try_get_special_node"] += special_count

    text, global_position_count = rewrite_inline_creature_global_positions(text)
    if global_position_count:
        counts["inline_global_position_or_zero"] += global_position_count

    text, nullable_counts = rewrite_nullable_var_accesses(text)
    counts.update(nullable_counts)

    if not counts:
        return text, counts

    text = ensure_helpers_using(text)
    header = (
        "// AUTO-GENERATED FILE. Source of truth is upstream src/ plus the\n"
        "// generator script STS2AI/ENV/Sim/scripts/generate_headless_model_compats.py.\n"
        "// Safe to regenerate; manual edits will be overwritten.\n\n"
    )
    if not text.startswith("// AUTO-GENERATED FILE."):
        text = header + text
    return text, counts


def target_generated_path(source_path: Path) -> Path:
    rel = source_path.resolve().relative_to((REPO_ROOT / "src").resolve())
    return GENERATED_ROOT / rel


HELPER_SOURCE = """using Godot;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Models.Encounters;
using MegaCrit.Sts2.Core.Nodes;
using MegaCrit.Sts2.Core.Nodes.Combat;
using MegaCrit.Sts2.Core.Nodes.Rooms;
using MegaCrit.Sts2.Core.Nodes.Vfx.Utilities;

namespace MegaCrit.Sts2.Core.Helpers;

public static class HeadlessVisualCompat
{
\tpublic static NCreature? TryGetCreatureNode(Creature creature)
\t{
\t\treturn NCombatRoom.Instance?.GetCreatureNode(creature);
\t}

\tpublic static T? TryGetSpecialNode<T>(NCreature? creatureNode, string path) where T : Node
\t{
\t\treturn creatureNode?.GetSpecialNode<T>(path);
\t}

\tpublic static T? TryGetCurrentBodyNode<T>(NCreature? creatureNode, string path) where T : Node
\t{
\t\treturn (creatureNode?.Visuals?.GetCurrentBody() as Node)?.GetNodeOrNull<T>(path);
\t}

\tpublic static T? TryGetBackgroundNode<T>(string path) where T : Node
\t{
\t\treturn NCombatRoom.Instance?.Background?.GetNodeOrNull<T>(path);
\t}

\tpublic static Vector2 GetGlobalPositionOrZero(Node2D? node)
\t{
\t\treturn node?.GlobalPosition ?? Vector2.Zero;
\t}

\tpublic static Vector2 GetGlobalPositionOrZero(NCreature? creatureNode)
\t{
\t\treturn creatureNode?.GlobalPosition ?? Vector2.Zero;
\t}

\tpublic static Vector2 GetBodyScaleOrOne(NCreature? creatureNode)
\t{
\t\treturn creatureNode?.Body?.Scale ?? Vector2.One;
\t}

\tpublic static Vector2 GetCurrentBodyScaleOrOne(NCreature? creatureNode)
\t{
\t\treturn (creatureNode?.Visuals?.GetCurrentBody() as Node2D)?.Scale ?? Vector2.One;
\t}

\tpublic static float GetCurrentBodyScaleXOrOne(NCreature? creatureNode)
\t{
\t\treturn (creatureNode?.Visuals?.GetCurrentBody() as Node2D)?.Scale.X ?? 1f;
\t}

\tpublic static void TrySetPosition(Node2D? node, Vector2 value)
\t{
\t\tif (node != null)
\t\t{
\t\t\tnode.Position = value;
\t\t}
\t}

\tpublic static void TryOffsetPosition(Node2D? node, Vector2 delta)
\t{
\t\tif (node != null)
\t\t{
\t\t\tnode.Position += delta;
\t\t}
\t}

\tpublic static void TrySetGlobalPosition(Node2D? node, Vector2 value)
\t{
\t\tif (node != null)
\t\t{
\t\t\tnode.GlobalPosition = value;
\t\t}
\t}

\tpublic static void TrySetGlobalPosition(NCreature? creatureNode, Vector2 value)
\t{
\t\tif (creatureNode != null)
\t\t{
\t\t\tcreatureNode.GlobalPosition = value;
\t\t}
\t}

\tpublic static void TryAddChild(Node? parent, Node? child)
\t{
\t\tif (parent != null && child != null)
\t\t{
\t\t\tparent.AddChildSafely(child);
\t\t}
\t}

\tpublic static void TryAddCombatVfx(Node node)
\t{
\t\tNCombatRoom.Instance?.CombatVfxContainer?.AddChildSafely(node);
\t}

\tpublic static void TryAddBackCombatVfx(Node node)
\t{
\t\tNCombatRoom.Instance?.BackCombatVfxContainer?.AddChildSafely(node);
\t}

\tpublic static void TryAddGlobalUi(Node node)
\t{
\t\tNGame.Instance?.CurrentRunNode?.GlobalUi?.AddChildSafely(node);
\t}

\tpublic static void TrySetFabricatorBotFallPosition(NCreature? creatureNode)
\t{
\t\tif (creatureNode != null)
\t\t{
\t\t\tFabricatorNormal.SetBotFallPosition(creatureNode);
\t\t}
\t}

\tpublic static void TryScreenShake(ShakeStrength strength, ShakeDuration duration)
\t{
\t\tNGame.Instance?.ScreenShake(strength, duration);
\t}

\tpublic static void TryScreenShake(ShakeStrength strength, ShakeDuration duration, float angle)
\t{
\t\tNGame.Instance?.ScreenShake(strength, duration, angle);
\t}

\tpublic static void TryScreenShakeTrauma(ShakeStrength strength)
\t{
\t\tNGame.Instance?.ScreenShakeTrauma(strength);
\t}

\tpublic static void TryScreenRumble(ShakeStrength strength, ShakeDuration duration, RumbleStyle style)
\t{
\t\tNGame.Instance?.ScreenRumble(strength, duration, style);
\t}

\tpublic static void TryDoHitStop(ShakeStrength strength, ShakeDuration duration)
\t{
\t\tNGame.Instance?.DoHitStop(strength, duration);
\t}

\tpublic static Vector2 GetViewportCenterOrZero()
\t{
\t\treturn NGame.Instance?.GetViewportRect().Size / 2f ?? Vector2.Zero;
\t}
}
"""


def write_generated_props(generated_files: list[Path]) -> None:
    lines = ["<Project>", "  <ItemGroup>"]
    for generated_path in sorted(generated_files):
        source_rel = generated_path.resolve().relative_to(GENERATED_ROOT.resolve()).as_posix()
        upstream_rel = source_rel.replace("/", "\\")
        lines.append(
            f'    <Compile Remove="$(MSBuildThisFileDirectory)..\\..\\..\\..\\..\\src\\{upstream_rel}" />'
        )
    lines.append(
        '    <Compile Include="$(MSBuildThisFileDirectory)**\\*.cs" '
        'Link="SrcCompat\\AutoGenerated\\%(RecursiveDir)%(Filename)%(Extension)" />'
    )
    lines.append("  </ItemGroup>")
    lines.append("</Project>")
    GENERATED_ROOT.mkdir(parents=True, exist_ok=True)
    PROPS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def clean_generated_root() -> None:
    if not GENERATED_ROOT.exists():
        return
    for path in sorted(GENERATED_ROOT.rglob("*"), reverse=True):
        if path.is_file():
            path.unlink()
        elif path.is_dir():
            try:
                path.rmdir()
            except OSError:
                pass


def main() -> int:
    args = parse_args()
    candidates = load_candidates(args.report.resolve(), top=args.top, match=args.match)
    if not candidates:
        print("[generate_headless_model_compats] no candidates")
        return 0

    generated_paths: list[Path] = []
    generated_contents: dict[Path, str] = {}
    for source_path, score in candidates:
        output_path = target_generated_path(source_path)
        text = source_path.read_text(encoding="utf-8")
        rewritten, counts = apply_transforms(text)
        summary = ", ".join(f"{name}={count}" for name, count in sorted(counts.items())) or "no-op"
        print(f"[candidate] score={score:>2} src={source_path}")
        print(f"           dst={output_path}")
        print(f"           transforms: {summary}")
        if not counts:
            continue
        generated_paths.append(output_path)
        generated_contents[output_path] = rewritten

    if args.write_files:
        clean_generated_root()
        helper_path = GENERATED_ROOT / "Core" / "Helpers" / "HeadlessVisualCompat.cs"
        helper_path.parent.mkdir(parents=True, exist_ok=True)
        helper_path.write_text(HELPER_SOURCE, encoding="utf-8")
        for output_path, rewritten in generated_contents.items():
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(rewritten, encoding="utf-8")
        write_generated_props(generated_paths)
        print(f"[generate_headless_model_compats] wrote generated sources to: {GENERATED_ROOT}")
        print(f"[generate_headless_model_compats] wrote props file: {PROPS_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
