from __future__ import annotations

from pathlib import Path
from typing import Protocol

from ..domain import BattleState, EvalSummary


class BattleRuntime(Protocol):
    def reset(self, *, seed: str | None = None) -> BattleState: ...
    def get_state(self) -> BattleState: ...
    def step(self, action_index: int) -> BattleState: ...
    def close(self) -> None: ...


class Policy(Protocol):
    def infer(self, state: BattleState) -> dict[str, object]: ...
    def reset_episode(self) -> None: ...
    def observe_transition(self, state: BattleState, action_index: int, next_state: BattleState) -> None: ...
    def observe_intent_choice(self, state: BattleState, intent_index: int) -> None: ...
    def select_action(self, state: BattleState) -> int: ...
    def score_actions(self, state: BattleState) -> list[float]: ...


class Evaluator(Protocol):
    def evaluate(self, policy: Policy) -> list[EvalSummary]: ...


class CheckpointStore(Protocol):
    def save(self, version: str, model_state: dict[str, object]) -> Path: ...
    def load(self, version: str) -> dict[str, object]: ...
    def save_candidate(self, version: str, model_state: dict[str, object]) -> Path: ...
    def discard(self, path: Path | None) -> None: ...
    def write_active_version(self, version: str) -> Path: ...
    def read_active_version(self) -> str | None: ...
