from __future__ import annotations

from pathlib import Path
from typing import Callable, Protocol

from ..domain import BattleState, EvalSummary, SearchLabel, SearchRequest


class BattleRuntime(Protocol):
    def reset(self, *, seed: str | None = None) -> BattleState: ...
    def get_state(self) -> BattleState: ...
    def step(self, action_index: int) -> BattleState: ...
    def close(self) -> None: ...


class Policy(Protocol):
    def select_action(self, state: BattleState) -> int: ...
    def score_actions(self, state: BattleState) -> list[float]: ...
    def estimate_uncertainty(self, state: BattleState) -> float: ...


class SearchBackend(Protocol):
    def label_request(
        self,
        request: SearchRequest,
        runtime_factory: Callable[[], BattleRuntime] | None = None,
        seed: str | None = None,
        policy: Policy | None = None,
    ) -> SearchLabel: ...


class Evaluator(Protocol):
    def evaluate(self, policy: Policy) -> list[EvalSummary]: ...


class CheckpointStore(Protocol):
    def save(self, version: str, model_state: dict[str, object]) -> Path: ...
    def load(self, version: str) -> dict[str, object]: ...
    def save_candidate(self, version: str, model_state: dict[str, object]) -> Path: ...
    def discard(self, path: Path | None) -> None: ...
    def write_active_version(self, version: str) -> Path: ...
    def read_active_version(self) -> str | None: ...
